### ISSUE TITLE
This module should not be used in runtime. Instead, use a transformer during compilation.

### ISSUE THREAD

**Issue by genesst** [woutervh-/typescript-is#101]
I'm trying to make `typescript-is` work in a Lambda runtime. Lambda is being deployed with AWS CDK.

`cdk.json`:
```
{
  "app": "npx ts-node --compiler ttypescript --prefer-ts-exts index.ts",
}
```

`package.json`:
```
"devDependencies": {
    ...
    "ttypescript": "^1.5.12",
    "typescript": "~4.2.4",
    ...
}
"dependencies": {
    ...
    "typescript-is": "^0.18.2",
    ...
}
```

`tsconfig.`:
```
{
  "compilerOptions": {
    "target": "ES2018",
    "module": "commonjs",
    "lib": ["es2018", "DOM"],
    "declaration": true,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": false,
    "inlineSourceMap": true,
    "inlineSources": true,
    "experimentalDecorators": true,
    "strictPropertyInitialization": false,
    "typeRoots": ["./node_modules/@types"],
    "baseUrl": "./",
    "plugins": [{
      "transform": "typescript-is/lib/transform-inline/transformer"
    }],
  },
  "exclude": ["cdk.out"]
}
```

Adding `"verbose": true` to plugins confirms that transformer is working. But when the function is being invoked it throws an error with the following stack:
```
"Error: This module should not be used in runtime. Instead, use a transformer during compilation.",
        "    at checkGetErrorObject (/var/task/index.js:33115:13)",
        "    at is2 (/var/task/index.js:33179:5)",
        ...
```

Would you suggest anything?

**Comment by mattddean** [comment]
Did you find a solution to this?
