### ISSUE TITLE
 TypeGuardError: validation failed at $: validation failed at $: superfluous property 'username' in object

### ISSUE THREAD

**Issue by LoganDark** [woutervh-/typescript-is#21]
```typescript
interface HasPassword {
	password: string
}

interface HasUsername {
	username: string
}

type UsernamePassword = HasPassword & HasUsername

const object = {username: 'test', password: 'test'}

try {
	assertType<UsernamePassword>(object)
} catch (e) {
	console.log(e)
}
```

Result:

```
TypeGuardError: validation failed at $: validation failed at $: superfluous property 'username' in object
    at Object.assertType (/Users/LoganDark/nitrogen/backend/node_modules/typescript-is/index.js:58:15)
    at Object.<anonymous> (/Users/LoganDark/nitrogen/backend/index.ts:239:5)
    at step (/Users/LoganDark/nitrogen/backend/index.ts:32:23)
    at Object.next (/Users/LoganDark/nitrogen/backend/index.ts:13:53)
    at /Users/LoganDark/nitrogen/backend/index.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/LoganDark/nitrogen/backend/index.ts:3:12)
    at /Users/LoganDark/nitrogen/backend/index.ts:224:16
    at Layer.handle [as handle_request] (/Users/LoganDark/nitrogen/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/LoganDark/nitrogen/backend/node_modules/express/lib/router/route.js:137:13) +1ms
```

Ignore the line numbers, I simplified the code for the issue.

Configuration:

```
{
	"transform": "typescript-is/lib/transform-inline/transformer",
	"ignoreClasses": true,
	"ignoreMethods": true,
	"disallowSuperfluousObjectProperties": true
}
```

The object does have `username` and `password` keys and they are both strings.

**Comment by woutervh-** [comment]
Hi @LoganDark 

Thanks for reporting the issue. I agree, it is falsely reporting superfluous properties. The reason it fails here is because it's trying to check for superfluous properties on `HasUsername` and `HasPassword` separately while the object should have properties from both interfaces. I will work on a fix, will let you know when I get some progress on it. 👍

**Comment by LoganDark** [comment]
@woutervh- Thank you for looking into it, please do so soon since my deadline is the 17th

**Comment by woutervh-** [comment]
Hi @LoganDark 

I believe I have a fix. Please check the new version `0.11.1`. Let me know if it works.

🤞

**Comment by LoganDark** [comment]
```
130 LoganDark ~/nitrogen/backend npm update typescript-is
npm WARN hexazine@1.1.0 No description
npm WARN hexazine@1.1.0 No repository field.

+ typescript-is@0.11.1
```

```
TypeGuardError: validation failed at $: validation failed at $: superfluous property 'username' in object
    at Object.assertType (/Users/LoganDark/nitrogen/backend/node_modules/typescript-is/index.js:58:15)
    at Object.<anonymous> (/Users/LoganDark/nitrogen/backend/index.ts:239:5)
    at step (/Users/LoganDark/nitrogen/backend/index.ts:32:23)
    at Object.next (/Users/LoganDark/nitrogen/backend/index.ts:13:53)
    at /Users/LoganDark/nitrogen/backend/index.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/LoganDark/nitrogen/backend/index.ts:3:12)
    at /Users/LoganDark/nitrogen/backend/index.ts:224:16
    at Layer.handle [as handle_request] (/Users/LoganDark/nitrogen/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/LoganDark/nitrogen/backend/node_modules/express/lib/router/route.js:137:13) +2ms
```

**Comment by LoganDark** [comment]
What I would do is build a list of all properties in either interface, and then check against that instead of any one interface. Not sure how your code works, because it looks incredibly complex to me, but it could be worth a try.

**Comment by LoganDark** [comment]
Any updates? I have a deadline to make.

**Comment by woutervh-** [comment]
Hey @LoganDark 

Are you sure you're on the latest version? With your types I'm getting correct code. I'm running https://github.com/woutervh-/typescript-is/blob/master/test/issue-21.ts with `"disallowSuperfluousObjectProperties": true` and getting the following code generated:

```typescript
{
	var path = ["$"];
	function _string(object) {
		if (typeof object !== "string")
			return "validation failed at " + path.join(".") + ": expected a string";
		else
			return null;
	}
	function _2899(object) {
		if (typeof object !== "object" || object === null || Array.isArray(object))
			return "validation failed at " + path.join(".") + ": expected an object"; {
			if ("password" in object) {
				path.push("password");
				var error = _string(object["password"]);
				path.pop();
				if (error)
					return error;
			} else
				return "validation failed at " + path.join(".") + ": expected 'password' in object";
		}
		return null;
	}
	function _2900(object) {
		if (typeof object !== "object" || object === null || Array.isArray(object))
			return "validation failed at " + path.join(".") + ": expected an object"; {
			if ("username" in object) {
				path.push("username");
				var error = _string(object["username"]);
				path.pop();
				if (error)
					return error;
			} else
				return "validation failed at " + path.join(".") + ": expected 'username' in object";
		}
		return null;
	}
	function _2901_s(object) {
		var conditions = [_2899, _2900];
		for (const condition of conditions) {
			var error = condition(object);
			if (error)
				return error;
		}
		for (const key of Object.keys(object)) {
			if (key !== "password" && key !== "username") // <-------- checking for username and password
				return "validation failed at " + path.join(".") + ": superfluous property '" + key + "' in object";
		}
		return null;
	}
	var error = _2901_s(object);
	return error;
}
```

Maybe your compiler cached an old version or something?
If you're definitely on version `0.11.1` then can you also give your `node` `npm` `ttypescript` `typescript` etc. versions?

**Comment by LoganDark** [comment]
> Maybe your compiler cached an old version or something?

Something like that. It works now...

Thank you so much for looking into this!

**Comment by artus9033** [comment]
I believe this is still an issue, at least with `typescript@4.7.4`. The below code is sufficient as a MWE for reproduction:
```typescript
type U1 = { username: string };
type U2 = { password: string };
type UserIntersection = U1 & U2;

let user = { username: "usr", password: "pwd" };

console.log(assertEquals<UserIntersection>(user));
```
which throws:
```
TypeGuardError: validation failed at user: superfluous property 'password' in object, found: { username: 'usr', password: 'pwd' }
```. That same behaviour is for `assertType` with the strict superfluous property checking enabled. This seems to be the same problem, probably due to some `typescript` changes, as after swapping the order of `U1 & U2` intersection to `U2 & U1`, the property `username` becomes guilty for the error, which would mean that only the first intersection type is taken into account by `typescript-is`.

@woutervh- this seems to be an important thing, could you review?
