### ISSUE TITLE
"Unsupported declaration kind" when validating against a class containing a method

### ISSUE THREAD

**Issue by geomaster** [woutervh-/typescript-is#3]
**ttypescript version**: 3.2.4
**typescript-is version**: 0.7.16
**node version**: 11.6.0

**Steps to reproduce**:
Try compiling a file containing the following:
```typescript
import { is } from 'typescript-is';

class X {
    method() {}
}
console.log(is<X>(new X()));
```

**Actual results**:
The compilation fails with an error like this:
```
typescript-is: transforming program with 23 source files; using TypeScript 3.2.4.

undefined:86995
                throw e;
                ^
NestedError: Failed to transform node at: /home/geomaster/Projects/tests/typescript-is/index.ts:6:13
    at transformNodeAndChildren (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript-is/lib/transform-inline/transformer.js:27:15)
    at ts.visitEachChild (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript-is/lib/transform-inline/transformer.js:29:62)
    at visitNodes (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript/lib/typescript.js:63441:48)
    at Object.visitEachChild (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript/lib/typescript.js:63610:156)
    at transformNodeAndChildren (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript-is/lib/transform-inline/transformer.js:29:15)
    at ts.visitEachChild (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript-is/lib/transform-inline/transformer.js:29:62)
    at visitNode (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript/lib/typescript.js:63390:23)
    at Object.visitEachChild (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript/lib/typescript.js:63664:59)
    at transformNodeAndChildren (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript-is/lib/transform-inline/transformer.js:29:15)
    at ts.visitEachChild (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript-is/lib/transform-inline/transformer.js:29:62)
Caused By: Error: Unsupported declaration kind: 156
    at visitDeclaration (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript-is/lib/transform-inline/visitor.js:52:15)
    at visitPropertySymbol (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript-is/lib/transform-inline/visitor.js:77:25)
    at visitRegularObjectType (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript-is/lib/transform-inline/visitor.js:131:29)
    at visitObjectType (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript-is/lib/transform-inline/visitor.js:172:16)
    at Object.visitType (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript-is/lib/transform-inline/visitor.js:366:16)
    at createArrowFunction (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript-is/lib/transform-inline/transform-node.js:9:21)
    at Object.transformNode (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript-is/lib/transform-inline/transform-node.js:58:35)
    at transformNodeAndChildren (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript-is/lib/transform-inline/transformer.js:22:44)
    at ts.visitEachChild (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript-is/lib/transform-inline/transformer.js:29:62)
    at visitNodes (/home/geomaster/Projects/tests/typescript-is/node_modules/typescript/lib/typescript.js:63441:48)
```

**Expected results**:
I know that class validation is explicitly not supported, which is completely fine. But this only breaks when the class has a method, which is a bit hard to track down and confusing. It might be more intuitive to display a normal compile error as soon as a class is tested. 

This is not a high-priority issue, but might be good to put it on the backlog - I had quite some trouble trying to figure out what exactly is happening here :)

**Comment by woutervh-** [comment]
Thanks @geomaster , I've made a fix, please try version 0.7.17.

(Commit: https://github.com/woutervh-/typescript-is/commit/efea60223ccc20e29e97dd20ea0652ab1bc0e8ce)

**Comment by woutervh-** [comment]
Hi @geomaster 

I have tried it myself as well with your minimal reproduction example:
```typescript
import { is } from 'typescript-is';

class X {
    method() {}
}
console.log(is<X>(new X()));
```

I'm getting the correct error message:

```
NestedError: Failed to transform node at: C:/Users/vanheewo/workspace/temp/src/index.ts:7:13
    at transformNodeAndChildren (C:\Users\vanheewo\workspace\temp\node_modules\typescript-is\lib\transform-inline\transformer.js:27:15)
    at ts.visitEachChild (C:\Users\vanheewo\workspace\temp\node_modules\typescript-is\lib\transform-inline\transformer.js:29:62)
    at visitNodes (C:\Users\vanheewo\workspace\temp\node_modules\typescript\lib\typescript.js:63441:48)
    at Object.visitEachChild (C:\Users\vanheewo\workspace\temp\node_modules\typescript\lib\typescript.js:63610:156)
    at transformNodeAndChildren (C:\Users\vanheewo\workspace\temp\node_modules\typescript-is\lib\transform-inline\transformer.js:29:15)
    at ts.visitEachChild (C:\Users\vanheewo\workspace\temp\node_modules\typescript-is\lib\transform-inline\transformer.js:29:62)
    at visitNode (C:\Users\vanheewo\workspace\temp\node_modules\typescript\lib\typescript.js:63390:23)
    at Object.visitEachChild (C:\Users\vanheewo\workspace\temp\node_modules\typescript\lib\typescript.js:63664:59)
    at transformNodeAndChildren (C:\Users\vanheewo\workspace\temp\node_modules\typescript-is\lib\transform-inline\transformer.js:29:15)
    at ts.visitEachChild (C:\Users\vanheewo\workspace\temp\node_modules\typescript-is\lib\transform-inline\transformer.js:29:62)
Caused By: Error: Classes cannot be validated. Please check the README.
    at Object.visitType (C:\Users\vanheewo\workspace\temp\node_modules\typescript-is\lib\transform-inline\visitor.js:367:19)
    at createArrowFunction (C:\Users\vanheewo\workspace\temp\node_modules\typescript-is\lib\transform-inline\transform-node.js:9:21)
    at Object.transformNode (C:\Users\vanheewo\workspace\temp\node_modules\typescript-is\lib\transform-inline\transform-node.js:58:35)
    at transformNodeAndChildren (C:\Users\vanheewo\workspace\temp\node_modules\typescript-is\lib\transform-inline\transformer.js:22:44)
    at ts.visitEachChild (C:\Users\vanheewo\workspace\temp\node_modules\typescript-is\lib\transform-inline\transformer.js:29:62)
    at visitNodes (C:\Users\vanheewo\workspace\temp\node_modules\typescript\lib\typescript.js:63441:48)
    at Object.visitEachChild (C:\Users\vanheewo\workspace\temp\node_modules\typescript\lib\typescript.js:63610:156)
    at transformNodeAndChildren (C:\Users\vanheewo\workspace\temp\node_modules\typescript-is\lib\transform-inline\transformer.js:29:15)
    at ts.visitEachChild (C:\Users\vanheewo\workspace\temp\node_modules\typescript-is\lib\transform-inline\transformer.js:29:62)
    at visitNode (C:\Users\vanheewo\workspace\temp\node_modules\typescript\lib\typescript.js:63390:23)
```

Could there be something different with your settings? If possible a minimal repo with all the config included could be helpful to reproduce it.

**Comment by geomaster** [comment]
Yep, looks like it's working. I must have made a mistake when re-testing. Thanks!
