### ISSUE TITLE
Fails to transform on empty tuples

### ISSUE THREAD

**Issue by matAtWork** [woutervh-/typescript-is#35]
Sample :
```
import { assertType } from 'typescript-is';

type Works = [number];
assertType<Works>([0]);

type Fails = [];
assertType<Fails>([]);
```

If you comment out the final line, all is good, if you don't you get (at compile time):
```
NestedError: Failed to transform node at: _test/ex.ts:6:17
    at transformNodeAndChildren (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:33:15)
    at ts.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:62)
    at visitNode (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67586:23)
    at Object.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67860:59)
    at transformNodeAndChildren (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:15)
    at ts.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:62)
    at visitNodes (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67637:48)
    at visitLexicalEnvironment (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67670:22)
    at Object.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67974:54)
    at transformNodeAndChildren (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:15)
Caused By: Error: Expected tuple type to have type arguments.
    at visitTupleObjectType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-name.js:10:15)
    at visitObjectType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-name.js:46:16)
    at Object.visitType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-name.js:114:16)
    at visitTupleObjectType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:12:34)
    at visitObjectType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:161:16)
    at visitType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:347:16)
    at visitTypeReference (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:143:20)
    at Object.visitType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:339:16)
    at createArrowFunction (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transform-node.js:16:36)
    at Object.transformNode (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transform-node.js:60:35)
```

Awesome project BTW.

**Comment by woutervh-** [comment]
Hi @matAtWork 

Thanks for the report, nice find! I will get a fix ready and let you know about a the release.

**Comment by woutervh-** [comment]
Fixed:
https://github.com/woutervh-/typescript-is/releases/tag/v0.12.6

Regression test:
https://github.com/woutervh-/typescript-is/blob/master/test/issue-35.ts

**Comment by matAtWork** [comment]
Thanks for the fix - I'll update our project and let you know if anything else is amiss
