### ISSUE TITLE
NestedException on transforming a type

### ISSUE THREAD

**Issue by matAtWork** [woutervh-/typescript-is#42]
**_It might be easier to read from the bottom as I simplified and narrowed down the source of the error over time_**

I get the following exception having updated a type. The update is non-trivial, and I've been unable (so far) to pin down the exact cause, but here's the jist of what the type is.

It represents a set of jobs, each of which is an async function with either parameters in an array via a `params` member, or a single parameter via a `param` member, like this:

```
interface ValidJobs {
  testJob: typeof testJob,
  rolloverJob: typeof rolloverJob,
  replicationTask: typeof replicationTask,
  processOutstanding: typeof processOutstanding,
}

type GenericJobFunction = (...args: any[]) => Promise<any>;
type JobParams<J extends GenericJobFunction> = Parameters<J> extends { length: 1 }
  ? { params: Parameters<J> } | { param: Parameters<J>[0] }
  : Parameters<J> extends { length: 0 } 
    ? undefined 
    : { params: Parameters<J> }

type JobSpec<J extends GenericJobFunction> = {
  runsOn?: Roles[] | undefined | null | false,
  interval: number | 'startup' | 'never'; 
  timeout?: number; 
} & JobParams<J>

export type Jobs = {
  [jobName in keyof ValidJobs]?: JobSpec<ValidJobs[jobName]> | false;
};
```

A sample of the object passed to validate is something like:
```json
{
  "rolloverJob": {
    "interval":3,
    "param":{"key":"837hdy487srt56x" }
  },
  "replicationTask": {
    "interval":10,
    "params":[12,"hourly check"]
  },
  "processOutstanding": {
    "interval":5,
    "runsOn": ["masternodes"]
  },
}
```

The previous version of the type was much less strict about defining the relationship between the keys of `Jobs` and the parameters (ie it was possible to pass parameters for one job to the definition of another).

Obviously, if I do find what causes/suppresses the error I'll let you know, but I'm hoping the stack dump & defns will point you (and therefore me!) in the right direction.

Version: `"typescript-is": "^0.13.0"`

```
NestedError: Failed to transform node at: /Users/matthew.woolf/git/news-search/f-extract/config/index.ts:175:13
    at transformNodeAndChildren (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:33:15)
    at ts.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:62)
    at visitNode (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67586:23)
    at Object.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67814:45)
    at transformNodeAndChildren (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:15)
    at ts.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:62)
    at visitNode (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67586:23)
    at Object.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67846:52)
    at transformNodeAndChildren (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:15)
    at ts.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:62)
Caused By: Error: Could not generate type-check; unsupported type with flags: 16777216
    at visitType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:369:15)
    at ts.createFunctionDeclaration.ts.createBlock.propertyInfos.map (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:100:23)
    at Array.map (<anonymous>)
    at VisitorUtils.setFunctionIfNotExists (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:94:30)
    at Object.setFunctionIfNotExists (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-utils.js:34:46)
    at visitRegularObjectType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:76:25)
    at visitObjectType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:168:16)
    at visitType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:346:16)
    at intersectionType.types.map (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:202:72)
    at Array.map (<anonymous>)
```

**Comment by matAtWork** [comment]
I had a go at digging around in the transformer, and I think it may be one of those cases where the generic type parameters mean it can't resolve something to generate a concrete check. This is true (probably) for some of the intermediate types before the `export Jobs`, but not for the entity as a whole - when considered from the PoV of the export, nothing is "variable" or external about the type.

**Comment by matAtWork** [comment]
If I collapse the whole type graph down, and in particular use `Parameters` at the top rather than repeatedly referring to it in `JobSpec`, I get the same error referring to type `J` rather than `Parameters`.

The new defn is:
```
type JobSpec<J extends Array<any>> = {
  runsOn?: Roles[] | undefined | null | false,
  interval: number | 'startup' | 'never'; 
  timeout?: number; 
} & (J extends { length: 1 }
  ? { params: J } | { param: J[0] }
  : J extends { length: 0 } 
    ? undefined 
    : { params: J })

export type Jobs = {
  [jobName in keyof ValidJobs]?: JobSpec<Parameters<ValidJobs[jobName]>> | false;
};
```

```
NestedError: Failed to transform node at: /Users/matthew.woolf/git/news-search/f-extract/config/index.ts:175:13
    at transformNodeAndChildren (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:33:15)
    at ts.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:62)
    at visitNode (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67586:23)
    at Object.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67814:45)
    at transformNodeAndChildren (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:15)
    at ts.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:62)
    at visitNode (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67586:23)
    at Object.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67846:52)
    at transformNodeAndChildren (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:15)
    at ts.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:62)
Caused By: Error: Could not generate type-check; unsupported type with flags: 33554432
    at visitType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:369:15)
    at ts.createFunctionDeclaration.ts.createBlock.propertyInfos.map (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:100:23)
    at Array.map (<anonymous>)
    at VisitorUtils.setFunctionIfNotExists (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:94:30)
    at Object.setFunctionIfNotExists (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-utils.js:34:46)
    at visitRegularObjectType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:76:25)
    at visitObjectType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:168:16)
    at visitType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:346:16)
    at intersectionType.types.map (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:202:72)
    at Array.map (<anonymous>)
```

**Comment by matAtWork** [comment]
....and if I take out all the generics from the type, except those used for `Parameters` (which), like this:

```
export type Jobs = {
  [jobName in keyof ValidJobs]?: {
    runsOn?: Roles[] | undefined | null | false,
    interval: number | 'startup' | 'never'; 
    timeout?: number; 
  } & (Parameters<ValidJobs[jobName]> extends { length: 1 }
    ? { params: Parameters<ValidJobs[jobName]> } | { param: Parameters<ValidJobs[jobName]>[0] }
    : Parameters<ValidJobs[jobName]> extends { length: 0 } 
      ? undefined 
      : { params: Parameters<ValidJobs[jobName]> }) | false;
};
```
...I get a similar trace:
```
NestedError: Failed to transform node at: /Users/matthew.woolf/git/news-search/f-extract/config/index.ts:175:13
    at transformNodeAndChildren (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:33:15)
    at ts.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:62)
    at visitNode (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67586:23)
    at Object.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67814:45)
    at transformNodeAndChildren (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:15)
    at ts.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:62)
    at visitNode (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67586:23)
    at Object.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67846:52)
    at transformNodeAndChildren (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:15)
    at ts.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:62)
Caused By: Error: Could not generate type-check; unsupported type with flags: 16777216
    at visitType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:369:15)
    at ts.createFunctionDeclaration.ts.createBlock.propertyInfos.map (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:100:23)
    at Array.map (<anonymous>)
    at VisitorUtils.setFunctionIfNotExists (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:94:30)
    at Object.setFunctionIfNotExists (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-utils.js:34:46)
    at visitRegularObjectType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:76:25)
    at visitObjectType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:168:16)
    at visitType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:346:16)
    at intersectionType.types.map (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:202:72)
    at Array.map (<anonymous>)
```

**Comment by matAtWork** [comment]
Ok, some progress. If I manually flatten out the references to `Parameters`, so I end up with the type:
```
export type Jobs = {
  [jobName in keyof ValidJobs]?: {
    runsOn?: Roles[] | undefined | null | false,
    interval: number | 'startup' | 'never'; 
    timeout?: number; 
  } & (ValidJobs[jobName] extends (arg: infer P) => any 
    ? { param: P } /* | { params: [P] } */
    : ValidJobs[jobName] extends (args: infer Q) => any
      ? { params: Q }
      : never)
}
```
...it transforms without error (although the app complains as the type is no incorrect). 

When I comment the ` | { params: [P] }` back in, it fails with:
```
NestedError: Failed to transform node at: /Users/matthew.woolf/git/news-search/f-extract/config/index.ts:175:13
    at transformNodeAndChildren (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:33:15)
    at ts.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:62)
    at visitNode (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67586:23)
    at Object.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67814:45)
    at transformNodeAndChildren (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:15)
    at ts.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:62)
    at visitNode (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67586:23)
    at Object.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67846:52)
    at transformNodeAndChildren (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:15)
    at ts.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:62)
Caused By: Error: Unbound type parameter, missing type node.
    at visitTypeParameter (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:150:15)
    at visitType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:342:16)
    at ts.createFunctionDeclaration.ts.createBlock.propertyInfos.map (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:100:23)
    at Array.map (<anonymous>)
    at VisitorUtils.setFunctionIfNotExists (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:94:30)
    at Object.setFunctionIfNotExists (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-utils.js:34:46)
    at visitRegularObjectType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:76:25)
    at visitObjectType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:168:16)
    at visitType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:346:16)
    at intersectionType.types.map (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:202:72)
```
....which is quite a different error

**Comment by matAtWork** [comment]
I've been playing with this on and off during the afternoon.

This one transforms:
```
export type Jobs = {
  [jobName in keyof ValidJobs]?: {
    runsOn?: Roles[] | undefined | null | false,
    interval: number | 'startup' | 'never'; 
    timeout?: number; 
  } & (ValidJobs[jobName] extends (...arg: infer P) => any 
    ? P extends [any] ? { param: P | P[0] } : { params: P }
      : never)
}
```
....and this one doesn't:
```
export type Jobs = {
  [jobName in keyof ValidJobs]?: {
    runsOn?: Roles[] | undefined | null | false,
    interval: number | 'startup' | 'never'; 
    timeout?: number; 
  } & (ValidJobs[jobName] extends (...arg: infer P) => any 
    ? P extends [any] ? { params: P | P[0] } : { params: P }
      : never)
}
```
The only difference is the name `param` or `params` in the final conditional clause. Repeating the name seems to upset the transformer. Note that TS itself is fine with all these examples

The error case is:
```
NestedError: Failed to transform node at: /Users/matthew.woolf/git/news-search/f-extract/config/index.ts:175:13
    at transformNodeAndChildren (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:33:15)
    at ts.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:62)
    at visitNode (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67586:23)
    at Object.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67814:45)
    at transformNodeAndChildren (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:15)
    at ts.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:62)
    at visitNode (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67586:23)
    at Object.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript/lib/typescript.js:67846:52)
    at transformNodeAndChildren (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:15)
    at ts.visitEachChild (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/transformer.js:35:62)
Caused By: Error: Could not generate type-check; unsupported type with flags: 33554432
    at visitType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-name.js:132:15)
    at type.types.map (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-name.js:56:44)
    at Array.map (<anonymous>)
    at visitUnionOrIntersectionType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-name.js:56:30)
    at Object.visitType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-name.js:120:16)
    at visitUnionOrIntersectionType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:192:38)
    at visitType (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:354:16)
    at ts.createFunctionDeclaration.ts.createBlock.propertyInfos.map (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:100:23)
    at Array.map (<anonymous>)
    at VisitorUtils.setFunctionIfNotExists (/Users/matthew.woolf/git/news-search/f-extract/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:94:30)

```

**Comment by matAtWork** [comment]
....and one final one before I give in today:
```
export type Jobs = {
  [jobName in keyof ValidJobs]?: {
    runsOn?: Roles[] | undefined | null | false,
    interval: number | 'startup' | 'never'; 
    timeout?: number;
    params: ValidJobs[jobName] extends (...args: infer P) => any ? P : undefined;
  } 
```
....this is much closer to the origin decl which worked (`params` was simply a union of the `Parameter` tuples for each possible function). So maybe the common theme is the use of `ValidJobs[jobName]`?

**Comment by woutervh-** [comment]
Hi @matAtWork 

The error "unsupported type with flags: 16777216" is due to the conditional type.
typescript-is does not support conditional types at the moment.
Usually, however, the TypeScript compiler evaluates conditional types, and simplifies them to the type they evaluate to.
I'm not sure why it does not do that in this case, I'll have to investigate that.

I think supporting conditional types will take a lot of effort, so it would be best if we can find out how to convince the TypeScript compiler to simplify those types.

**Comment by woutervh-** [comment]
By replacing `ValidJobs[jobName] extends (...args: infer P) => any ? P : undefined` with `Parameters<ValidJobs[jobName]>` I managed to get it to work. Is this what you also tried in #43? :)

**Comment by woutervh-** [comment]
Closing for housekeeping.
