### ISSUE TITLE
is<Isomething>() -> NestedError: Failed to transform node

### ISSUE THREAD

**Issue by khmseu** [woutervh-/typescript-is#5]
[attach.zip](https://github.com/woutervh-/typescript-is/files/2800026/attach.zip)

kai@desktop:/bigdata/KAI/projects/Mechanic$ ./prepare-checkin.sh 
yarn run v1.13.0
$ ttsc
typescript-is: transforming program with 98 source files; using TypeScript 3.2.4.

/bigdata/KAI/projects/Mechanic/node_modules/typescript/lib/typescript.js:86995
                throw e;
                ^
NestedError: Failed to transform node at: /bigdata/KAI/projects/Mechanic/src/io/readRuleFile.ts:28:19
    at transformNodeAndChildren (/bigdata/KAI/projects/Mechanic/node_modules/typescript-is/lib/transform-inline/transformer.js:27:15)
    at ts.visitEachChild (/bigdata/KAI/projects/Mechanic/node_modules/typescript-is/lib/transform-inline/transformer.js:29:62)
    at visitNode (/bigdata/KAI/projects/Mechanic/node_modules/typescript/lib/typescript.js:63390:23)
    at Object.visitEachChild (/bigdata/KAI/projects/Mechanic/node_modules/typescript/lib/typescript.js:63694:154)
    at transformNodeAndChildren (/bigdata/KAI/projects/Mechanic/node_modules/typescript-is/lib/transform-inline/transformer.js:29:15)
    at ts.visitEachChild (/bigdata/KAI/projects/Mechanic/node_modules/typescript-is/lib/transform-inline/transformer.js:29:62)
    at visitNodes (/bigdata/KAI/projects/Mechanic/node_modules/typescript/lib/typescript.js:63441:48)
    at Object.visitEachChild (/bigdata/KAI/projects/Mechanic/node_modules/typescript/lib/typescript.js:63696:63)
    at transformNodeAndChildren (/bigdata/KAI/projects/Mechanic/node_modules/typescript-is/lib/transform-inline/transformer.js:29:15)
    at ts.visitEachChild (/bigdata/KAI/projects/Mechanic/node_modules/typescript-is/lib/transform-inline/transformer.js:29:62)
Caused By: Error: Unsupported declaration kind: 155
    at visitDeclaration (/bigdata/KAI/projects/Mechanic/node_modules/typescript-is/lib/transform-inline/visitor.js:52:15)
    at visitPropertySymbol (/bigdata/KAI/projects/Mechanic/node_modules/typescript-is/lib/transform-inline/visitor.js:77:25)
    at visitRegularObjectType (/bigdata/KAI/projects/Mechanic/node_modules/typescript-is/lib/transform-inline/visitor.js:131:29)
    at visitObjectType (/bigdata/KAI/projects/Mechanic/node_modules/typescript-is/lib/transform-inline/visitor.js:172:16)
    at visitType (/bigdata/KAI/projects/Mechanic/node_modules/typescript-is/lib/transform-inline/visitor.js:371:20)
    at type.types.map (/bigdata/KAI/projects/Mechanic/node_modules/typescript-is/lib/transform-inline/visitor.js:213:24)
    at Array.map (<anonymous>)
    at visitUnionOrIntersectionType (/bigdata/KAI/projects/Mechanic/node_modules/typescript-is/lib/transform-inline/visitor.js:213:10)
    at visitType (/bigdata/KAI/projects/Mechanic/node_modules/typescript-is/lib/transform-inline/visitor.js:380:16)
    at visitArrayObjectType (/bigdata/KAI/projects/Mechanic/node_modules/typescript-is/lib/transform-inline/visitor.js:66:33)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by woutervh-** [comment]
hi @khmseu 
From the error I see there is an unsupported syntax kind `155` which is a constructor.
As this package is primarily used to validate serializable data, it does not support functions, classes, constructors, etc. The best I could do in that case is to simply check if it is a function, but that does not mean the function complies with the signature defined in TypeScript, so it's not very useful. I can't tell much more from the limited amount of source code you've attached. If you're trying to validate classes, then these are explicitly not supported.
However I think the error message could be nicer, so I'll aim to add that soon.

Hope that explains it.

**Comment by woutervh-** [comment]
I've added a more detailed error message when it encounters a method.
https://github.com/woutervh-/typescript-is/commit/7019c1e04401ca19e8a3e74aebdcea4cce60063c

It will be part of the next version.
I'll close the ticket for house keeping.

**Comment by woutervh-** [comment]
Also see https://github.com/woutervh-/typescript-is/issues/16
