### ISSUE TITLE
Transforming error on an interface extending a class including another class.

### ISSUE THREAD

**Issue by acomagu** [woutervh-/typescript-is#62]
Hi thank you for amazing product. I really love it.

```typescript
class A { }
class B {
  a?: A;
}
interface C extends B { }
assertType<C>({});
```

This throws like:

```
/proj/node_modules/typescript/lib/typescript.js:98681
                throw e;
                ^
NestedError: Failed to transform node at: /proj/index.ts:5:26
    at transformNodeAndChildren (/proj/node_modules/typescript-is/lib/transform-inline/transformer.js:35:15)
    at /proj/node_modules/typescript-is/lib/transform-inline/transformer.js:37:62
    at visitNode (/proj/node_modules/typescript/lib/typescript.js:73037:23)
    at Object.visitEachChild (/proj/node_modules/typescript/lib/typescript.js:73320:59)
    at transformNodeAndChildren (/proj/node_modules/typescript-is/lib/transform-inline/transformer.js:37:15)
    at /proj/node_modules/typescript-is/lib/transform-inline/transformer.js:37:62
    at visitNodes (/proj/node_modules/typescript/lib/typescript.js:73088:48)
    at visitLexicalEnvironment (/proj/node_modules/typescript/lib/typescript.js:73121:22)
    at Object.visitEachChild (/proj/node_modules/typescript/lib/typescript.js:73436:54)
    at transformNodeAndChildren (/proj/node_modules/typescript-is/lib/transform-inline/transformer.js:37:15)
Caused By: Error: Unsupported declaration kind: 159
    at Object.getPropertyInfo (/proj/node_modules/typescript-is/lib/transform-inline/visitor-utils.js:51:19)
    at /proj/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:84:111
    at Array.map (<anonymous>)
    at /proj/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:84:80
    at Object.setFunctionIfNotExists (/proj/node_modules/typescript-is/lib/transform-inline/visitor-utils.js:38:46)
    at visitRegularObjectType (/proj/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:83:25)
    at visitObjectType (/proj/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:177:16)
    at visitType (/proj/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:356:16)
    at visitTypeReference (/proj/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:142:20)
    at Object.visitType (/proj/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:348:16) {
  nested: Error: Unsupported declaration kind: 159
      at Object.getPropertyInfo (/proj/node_modules/typescript-is/lib/transform-inline/visitor-utils.js:51:19)
      at /proj/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:84:111
      at Array.map (<anonymous>)
      at /proj/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:84:80
      at Object.setFunctionIfNotExists (/proj/node_modules/typescript-is/lib/transform-inline/visitor-utils.js:38:46)
      at visitRegularObjectType (/proj/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:83:25)
      at visitObjectType (/proj/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:177:16)
      at visitType (/proj/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:356:16)
      at visitTypeReference (/proj/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:142:20)
      at Object.visitType (/proj/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:348:16)
}
```

I think at least this limitation should be explained at README.

env:

```
node: 13.11.0
ttypescript: 1.5.10
typescript: 3.8.3
typescript-is: 0.15.0
```

Thanks!

**Comment by acomagu** [comment]
Oh I understood why this error is caused because of [your comment](https://github.com/woutervh-/typescript-is/issues/20#issuecomment-484398130).

**Comment by acomagu** [comment]
Now I think this issue is not so critical problem(just the error message is not meaningful) so I close.
