### ISSUE TITLE
Bug with latest TypeScript + Mapped types

### ISSUE THREAD

**Issue by jarofghosts** [woutervh-/typescript-is#65]
I've been trying to upgrade TypeScript to 3.9 and am encountering an issue with using `typescript-is` with [mapped types](https://github.com/jarofghosts/typescript-is-bug/blob/master/index.ts#L8) in that version.

Minimal test case:
- clone https://github.com/jarofghosts/typescript-is-bug
- `npm ci`
- `npm test`

```
NestedError: Failed to transform node at: /Users/jesse.keane/Projects/personal/typescript-is-bug/index.ts:6:2
    at transformNodeAndChildren (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/transformer.js:35:15)
    at /Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/transformer.js:37:62
    at visitNode (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript/lib/typescript.js:74775:23)
    at Object.visitEachChild (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript/lib/typescript.js:75110:59)
    at transformNodeAndChildren (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/transformer.js:37:15)
    at /Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/transformer.js:37:62
    at visitNodes (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript/lib/typescript.js:74826:48)
    at visitLexicalEnvironment (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript/lib/typescript.js:74859:22)
    at Object.visitEachChild (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript/lib/typescript.js:75226:54)
    at transformNodeAndChildren (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/transformer.js:37:15)
Caused By: Error: Expected a valueDeclaration or a property type.
    at Object.getPropertyInfo (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/visitor-utils.js:90:19)
    at /Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:94:111
    at Array.map (<anonymous>)
    at /Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:94:80
    at Object.setFunctionIfNotExists (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/visitor-utils.js:37:46)
    at visitRegularObjectType (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:93:25)
    at visitObjectType (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:197:16)
    at Object.visitType (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:376:16)
    at createArrowFunction (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/transform-node.js:16:36)
    at Object.transformNode (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/transform-node.js:64:35) {
  nested: Error: Expected a valueDeclaration or a property type.
      at Object.getPropertyInfo (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/visitor-utils.js:90:19)
      at /Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:94:111
      at Array.map (<anonymous>)
      at /Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:94:80
      at Object.setFunctionIfNotExists (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/visitor-utils.js:37:46)
      at visitRegularObjectType (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:93:25)
      at visitObjectType (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:197:16)
      at Object.visitType (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/visitor-type-check.js:376:16)
      at createArrowFunction (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/transform-node.js:16:36)
      at Object.transformNode (/Users/jesse.keane/Projects/personal/typescript-is-bug/node_modules/typescript-is/lib/transform-inline/transform-node.js:64:35)
```

**Comment by woutervh-** [comment]
Hi @jarofghosts 

Thanks for the report. I will have a look and try to fix this for TypeScript 3.9

**Comment by woutervh-** [comment]
@jarofghosts 

Thanks again for the detailed report.
I think I have found a fix.

Please try the new release:
https://github.com/woutervh-/typescript-is/releases/tag/v0.16.2

**Comment by jarofghosts** [comment]
@woutervh- thanks for the quick fix, seems to be working now!
